spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile:
        - local
        - dev
        - prod
        - qa
  data:
    mongodb:
      host: localhost
      port: 27019
      database: local

---
spring:
  config:
    activate:
      on-profile:
        - test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
